// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Repo } from "./Repo";

export type CommitHead = { sha: string, ref: string, repo: Repo, };