// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines how Titanfall2 was installed (Steam, Origin, ...)
 */
export type InstallType = "STEAM" | "ORIGIN" | "EAPLAY" | "UNKNOWN";
