// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallState } from "./InstallState";

export type InstallProgress = { current_downloaded: bigint, total_size: bigint, state: InstallState, };
