// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface NorthstarMod { name: string, thunderstore_mod_string: string | null, enabled: boolean, directory: string, }