// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NorthstarThunderstoreRelease } from "./NorthstarThunderstoreRelease";

export interface NorthstarThunderstoreReleaseWrapper { label: string, value: NorthstarThunderstoreRelease, }