// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitHead } from "./CommitHead";

export interface PullsApiResponseElement { number: bigint, title: string, url: string, head: CommitHead, }