// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tag } from "./Tag";

/**
 * Wrapper type needed for frontend
 */
export type TagWrapper = { label: string, value: Tag, };
