name: "release"
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Needed to write to GitHub draft release

jobs:
  # Ensure version numbers in various places match up
  ensure-same-version:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: install dependencies
        run: |
          pip install toml
      - name: Run check
        run: |
          python3 scripts/check_version_numbers.py --release ${{github.ref_name}}

  build:
    needs: ensure-same-version
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-24.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v6
    - name: setup node
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-24.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils

    - name: Install frontend dependencies
      run: npm install

    - name: Compile and upload app
      uses: tauri-apps/tauri-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      with:
        tagName: v__VERSION__
        releaseName: 'v__VERSION__'
        releaseDraft: true
        prerelease: true
        uploadUpdaterJson: true
